#179: made more models work
RakipInitiative/landingpage pull request #6
Opened 2020-10-23 15:09 UTC by schuelet

most models run, though some are very slow (2min+) even on the default simulations
Package gsl does not work
Package r2OpenBugs can't find the openbugs program on the computer
IMPORTANT NOTE: PiresOutblA2011-Salmonells.fskx had a faulty Salmonella-all.csv file resource which I fixed manually (some entries had a newline character, breaking the file). R seems to ignore it, but Renjin (and KNIME CSV Reader) cant read the file properly).

2020-10-26 13:17 UTC, miguelalba requested changes
Some lesser problems are commented. The order of the parameters is lost in SED-ML document and generated simulation scripts for the model *Fitting Distribution for Microbial Counts* but I can restore the parameters order from the metadata where it's preserved.

2020-10-26 13:17 UTC, miguelalba commented on src/Server.kt
> +const val LOCAL_TEST = true // Set true for testing locally with netty.
We need to leave it false for it to run when deployed on Tomcat.

2020-10-26 13:17 UTC, miguelalba commented on src/Server.kt
> +            //val testModelPath = {}.javaClass.getResource("/static/files/preparedQuick.fskx").file
Please remove commented code.

2020-10-26 13:17 UTC, miguelalba commented on src/Server.kt
> +    var selectedSimulationIndex: Int,
Is selectedSimulationIndex necessary? We are taking the index from simulations in runSelectedSimulation.

2020-10-26 14:58 UTC, schuelet commented on src/Server.kt
> +    var selectedSimulationIndex: Int,
I dont know, this was already in master. We can change it once the simulation execution takes simulations.

2020-10-27 09:51 UTC, miguelalba reviewed
I am adding my commit with changes to the simulation.

2020-10-27 10:29 UTC, closed without merging

2020-10-28 08:35 UTC, miguelalba commented
This PR was replaced with https://github.com/RakipInitiative/landingpage/pull/8. @schuelet can we delete the branch?